CREATE TABLE study_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_study_groups_teacher FOREIGN KEY (teacher_id) REFERENCES users(id)
);

ALTER TABLE users ADD COLUMN group_id BIGINT NULL;
ALTER TABLE users ADD CONSTRAINT fk_users_group FOREIGN KEY (group_id) REFERENCES study_groups(id);

CREATE TABLE group_invites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    group_id BIGINT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_invites_teacher FOREIGN KEY (teacher_id) REFERENCES users(id),
    CONSTRAINT fk_invites_student FOREIGN KEY (student_id) REFERENCES users(id),
    CONSTRAINT fk_invites_group FOREIGN KEY (group_id) REFERENCES study_groups(id) ON DELETE SET NULL
);

CREATE INDEX idx_group_invites_student ON group_invites(student_id, status);
CREATE INDEX idx_group_invites_teacher ON group_invites(teacher_id, status);
